eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka


application:
  jwt:
    secret: pweb2-eh-legal
    expirationTimeInSeconds: 3600 
