server:
  port: 8082

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: secret
    url: jdbc:postgresql://localhost:5432/video-service
  jpa:
    hibernate:
      ddl-auto: none